sudo: required
dist: xenial
language: c
cache:
  ccache: true
  directories:
    - $HOME/miniconda

python:
  - "3.7"

before_install:
  - .travis/travis_before_install.sh
install:
  - export PATH=$HOME/miniconda3/bin:$PATH
  - .travis/travis_install.sh
script:
    - source activate condaenv
    - python -m pytest

